### Moduel 7.5: Practice Notebook on Module 07 Data Preprocessing and Feature Engineering

In the previous practice day (6.5), you had already chosen **one dataset** from the list below and repeated the full EDA steps you learned in Module 06. For today’s practice (7.5), you will work on the topics you learned in Module 07: Data Preprocessing and Feature Engineering.

### Dataset Options (Choose One)

1. E-Commerce Fraud Detection Dataset  
   https://www.kaggle.com/datasets/umuttuygurr/e-commerce-fraud-detection-dataset  

2. BreastDataset  
   https://www.kaggle.com/datasets/khansaafreen/breastdataset  

3. Titanic Dataset  
   https://www.kaggle.com/datasets/yasserh/titanic-dataset  

4. Loan Approval Dataset  
   https://www.kaggle.com/datasets/anishdevedward/loan-approval-dataset  

5. Diabetes Health Indicators Dataset  
   https://www.kaggle.com/datasets/mohankrishnathalla/diabetes-health-indicators-dataset  

6. Alzheimer’s Disease Dataset  
   https://www.kaggle.com/datasets/rabieelkharoua/alzheimers-disease-dataset  

7. Students Performance Dataset  
   https://www.kaggle.com/datasets/rabieelkharoua/students-performance-dataset  

8. Cancer Data  
   https://www.kaggle.com/datasets/erdemtaha/cancer-data  

9. Mushroom Classification  
   https://www.kaggle.com/datasets/uciml/mushroom-classification  

10. Rain in Australia  
   https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package  

---

### Section 13 — Handling Missing Values

In [11]:
# TODO
# Find Missing Values of your Dataset
# Identify which way you should impute those missing values
# Apply the methods to impute missing values
import pandas as pd
import numpy as np
titanic_path = "Titanic-Dataset.csv"
df_titanic = pd.read_csv(titanic_path)
df_titanic.isnull().sum()

# Handle missing value age
age_median = df_titanic["Age"].median()
df_titanic["Age"] = df_titanic["Age"].fillna(age_median)

# Handle categorical missing values
embarked_mode = df_titanic["Embarked"].mode()[0]
df_titanic["Embarked"] = df_titanic["Embarked"].fillna(embarked_mode)

df_titanic = df_titanic.drop(columns = ["Cabin"])

df_titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Section 14 — Encoding Categorical Variables

In [13]:
# TODO
# Identify categorical features
# Take decision on what encoding will you apply for each categorical features
# Apply the methods to encode the features and show final data

categorical_cols = ["Sex","ChestPainType"]
df_titanic["Sex"] = df_titanic["Sex"].map({ "male": 0,"female": 1 })

df_titanic = pd.get_dummies( df_titanic, columns=["Embarked"], drop_first=True )

df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,True

### Section 15 — Normalization and Scaling

In [20]:
# TODO
# Check if your dataset have features with different range of values or not
# Take decision on whether scaling is required or not
# If required apply one of the scaling method

from sklearn.preprocessing import StandardScaler
numerical_cols = ["Age", "Fare", "SibSp", "Parch"]

df_titanic[numerical_cols].describe()
scaler = StandardScaler()

df_titanic[numerical_cols] = scaler.fit_transform(
    df_titanic[numerical_cols]
)

df_titanic[numerical_cols].head()

        Age      Fare     SibSp     Parch
0 -0.565736 -0.502445  0.432793 -0.473674
1  0.663861  0.786845  0.432793 -0.473674
2 -0.258337 -0.488854 -0.474545 -0.473674
3  0.433312  0.420730  0.432793 -0.473674
4  0.433312 -0.486337 -0.474545 -0.473674